import { MaterialsProvider } from "@/components/MaterialsContext";
import Sidebar from "../components/Sidebar";
import { ItemClassificationsProvider } from "@/components/ItemClassificationsContext";

export const metadata = {
  title: "Pacific Fine Millwork",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* bg-[#F1F1F1] */}
      <body className="bg-[#E9EDF2] min-h-screen min-w-screen flex justify-between items-center">
        <Sidebar />
        <main className="h-[97vh] w-[94vw] px-6 mx-auto overflow-hidden">
          <ItemClassificationsProvider>
            <MaterialsProvider>{children}</MaterialsProvider>
          </ItemClassificationsProvider>
        </main>
      </body>
    </html>
  );
}
